### PR TITLE
Readable_role_operations

### PR DESCRIPTION
**Pull request by SaloEater**
And now it's possible to find logic mistake in the _Query_ class

### CODE REVIEW

**Comment by SaloEater** [comment]
@0ffz, can you let me know when you are about to merge development branch into master? I will update this branch once more.

**Comment by 0ffz** [comment]
Yeah I actually added really similar extensions for the front bits on dev but I like some of the extra ones you've made.

Will mention when the query rewrite is in with those. It will likely cause some merge conflicts but I like the changes here.

**Review by 0ffz — APPROVED** [review]
Let me know if this is ready to merge, it looks good!

**Comment by SaloEater** [comment]
It's ready to.

**Pull request merged**
